name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository  
        run: |
          cd /var/www/foodpos.yanlui.com;
          git checkout main;
          git pull origin main;
          composer install;
          php artisan config:claer;
          php artisan migrate;
          php artisan optimize;
          npm run build;


        
        
