name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_staging:
        description: 'Confirm to deploy? (Type Yes to proceed)'
        required: true
        default: 'No'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Only run this step if triggered manually
      - name: Confirm deploy
        id: confirm
        if: github.event_name == 'workflow_dispatch' && inputs.deploy_staging == 'Yes'
        run: echo "Deployment confirmed."

      # Execute deployment commands if confirmed or if triggered by push
      - name: Deploy to Main 
        if: github.event_name == 'workflow_dispatch' && inputs.deploy_staging == 'Yes' || github.event_name == 'push'
        run: |
          cd /var/www/foodpos.yanlui.com;
          git checkout main;
          git pull origin main;
          composer install;
          php artisan config:clear;
          php artisan migrate;
          php artisan optimize;
          npm ci;
          npm run build;