name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_staging:
        description: 'Confirm to deploy?'
        required: true
        default: 'No'
      
  push:
    branches:
      - main
jobs:
  deploy:

    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Confirm deploy
        id: confirm
        if: inputs.deploy_staging == 'Yes'
        run: 'echo Hello'



      - name: Deploy to Main 
        if: steps.confirm.outcome == 'success'
        run: |
          cd /var/www/foodpos.yanlui.com;
          git checkout main;
          git pull origin main;
          composer install;
          php artisan config:clear;
          php artisan migrate;
          php artisan optimize;
          npm ci;
          npm run build;


        
        
